version: '2'
services:
  app:
    image: hub.touchtech.co.nz/mememoji_api:latest-staging
    environment:
      VIRTUAL_HOST: tepapa-poc.touchtech.co.nz
      VIRTUAL_PORT: 5000
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
